[tool.poetry]
name = "source-dbt-duckdb"
version = "0.1.0"
description = "Airbyte Source implementation for Dbt DuckDB."
authors = ["Airbyte <contact@airbyte.io>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10,<4.0"

# airbyte-cdk = "^0.53.9"
dbt-duckdb = "^1.7.0"
# SQLAlchemy = "^2.0.23"
# duckdb = "^0.9.2"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.3"
pytest-mock = "^3.12.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
