[tool.poetry]
name = "source-dbt-duckdb"
version = "0.1.0"
description = "Airbyte Source implementation for Dbt DuckDB."
authors = ["Airbyte <contact@airbyte.io>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.9.18,<4.0"

# Toggle which version of the CDK to use by commenting/uncommenting the appropriate line below.
#
# Use a published version of the CDK:
# airbyte-cdk = "^0.53.9"
# OR use the local version of the CDK:
# airbyte-cdk = { path = "../../../airbyte-cdk/python", develop = true }
# OR temporary workaround because `airbyte-ci` doesn't have access to the local directory, and/or it is missing dependencies:
airbyte-cdk = { git = "https://github.com/airbytehq/airbyte.git", branch = "aj/source-dbt", develop = true, subdirectory = "airbyte-cdk/python" }

# Other dependencies
dbt-duckdb = "^1.7.0"
dbt = "^1.0.0.34.14"
# SQLAlchemy = "^2.0.23"
# duckdb = "^0.9.2"
dulwich = "^0.21.6"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.3"
pytest-mock = "^3.12.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
source-dbt-duckdb = "source_dbt_duckdb.cli:main"
