# Docs: https://docs.getdbt.com/reference/warehouse-profiles/duckdb-profile
duckdb_sample_project:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: "{{ env_var('DUCKDB_DB_DIR') }}/dev.duckdb"
      threads: 1

    prod:
      type: duckdb
      path: "{{ env_var('DUCKDB_DB_DIR') }}/prod.duckdb"
      threads: 4
