[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
version = "0.10.2"
name = "source-twilio"
description = "Source implementation for Twilio."
authors = ["Airbyte <contact@airbyte.io>"]
license = "MIT"
readme = "README.md"
documentation = "https://docs.airbyte.com/integrations/sources/twilio"
homepage = "https://airbyte.com"
repository = "https://github.com/airbytehq/airbyte"
[[tool.poetry.packages]]
include = "source_twilio"

[tool.poetry.dependencies]
python = "^3.9,<3.12"
pendulum = "<3"
requests = "==2.31.0"
airbyte-cdk = "^0.63.2"

[tool.poetry.scripts]
source-twilio = "source_twilio.run:run"

[tool.poetry.group.dev.dependencies]
pytest-mock = "^3.12.0"
freezegun = "^1.4.0"
requests-mock = "^1.9.3"
pytest = "^6.1"

[tool.pyright]
reportMissingImports = true
reportMissingTypeStubs = false
venvPath = "."
venv = ".venv"
