connector_version_left: "4.5.4"
_connector_version_right: "4.5.4"
connector_version_right: "5.0.1-dev.e4339d53e7"
streams:
  - name: customers
    ignore_fields:
      - hosted_invoice_url
      - invoice_pdf
  - name: invoices
    ignore_fields:
      - hosted_invoice_url
      - invoice_pdf