[tool.poetry]
name = "airbyte-lib"
description = "AirbyteLib"
version = "0.1.0"
authors = ["Airbyte <contact@airbyte.io>"]
readme = "README.md"
packages = [{include = "airbyte_lib"}]

[tool.poetry.dependencies]
python = "^3.10"

airbyte-cdk = "^0.57.6"
jsonschema = "3.2.0"
overrides = "^7.4.0"
pandas = "^2.1.4"
pyarrow = "^14.0.1"
python-ulid = "^2.2.0"
requests = "^2.31.0"
SQLAlchemy = "^2.0.23"

[tool.poetry.group.dev.dependencies]
mypy = "^1.7.1"
pytest = "^7.4.3"
ruff = "^0.1.7"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
