name: Community CI Spike

concurrency:
  # This is the name of the concurrency group. It is used to prevent concurrent runs of the same workflow.
  #
  # - github.head_ref is only defined on PR runs, it makes sure that the concurrency group is unique for pull requests
  #  ensuring that only one run per pull request is active at a time.
  #
  # - github.run_id is defined on all runs, it makes sure that the concurrency group is unique for workflow dispatches.
  # This allows us to run multiple workflow dispatches in parallel.
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}

on:
  pull_request_target:
jobs:
  # Only running connector CI for example
  # Other required checks should be added as new jobs in this workflow
  # e.g. format, Gradle check, CDK builds
  connectors_ci:
    name: Connectors CI
    runs-on: tooling-test-large
    timeout-minutes: 1440 # 24 hours
    permissions:
      statuses: write
      pull-requests: read
    steps:
      - run: echo "Running on community-ci environment"
        bash: shell
      - name: Checkout Airbyte
        uses: actions/checkout@v3
        with:
          # This checkouts the fork
          # /!\ untrusted code
          # It's deemed safe as running is job is running on:
          # - the community-ci environment
          # - gated by an approval from an Airbyter
          ref: refs/pull/${{ github.event.number }}/merge
          fetch-depth: 1
          persist-credentials: false

      - name: Test connectors
        if: github.event_name == 'pull_request_target'
        # The action running here is using the checked out code!
        # We should fail the workflow upstream if any changes to the .github folder are made on the fork
        uses: ./.github/actions/run-dagger-pipeline
        with:
          context: "pull_request"
          dagger_cloud_token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
          docker_hub_password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          docker_hub_username: ${{ secrets.DOCKER_HUB_USERNAME }}
          gcp_gsm_credentials: ${{ secrets.GCP_GSM_CREDENTIALS }}
          sentry_dsn: ${{ secrets.SENTRY_AIRBYTE_CI_DSN }}
          github_token: ${{ github.token }}
          s3_build_cache_access_key_id: ${{ secrets.SELF_RUNNER_AWS_ACCESS_KEY_ID }}
          s3_build_cache_secret_key: ${{ secrets.SELF_RUNNER_AWS_SECRET_ACCESS_KEY }}
          subcommand: "connectors --modified test"
          is_fork: ${{ github.event.pull_request.head.repo.fork }}
        