# Usage: This workflow can be invoked manually or by a slash command.
#
# To invoke via GitHub UI, go to Actions tab, select the workflow, and click "Run workflow".
#
# To invoke via slash command, use the following syntax in a comment on a PR:
#    /publish-java-cdk                # Run with the defaults (dry-run=false, force=false)
#    /publish-java-cdk dry-run=true   # Run in dry-run mode (no-op)
#    /publish-java-cdk force=true     # Force-publish if needing to replace an already published version
name: Publish Java CDK and Merge
on:
  push:
    branches:
      - stephane/01-24-add_publish-java-cdk-and-merge_command
  workflow_dispatch:
    inputs:
      repo:
        description: "Repo to check out code from. Defaults to the main airbyte repo."
        # TODO: If publishing from forks is needed, we'll need to revert type to `string` of `choice`.
        type: choice
        required: true
        default: airbytehq/airbyte
        options:
          - airbytehq/airbyte
      dry-run:
        description: "Dry run (no-op)"
        required: true
        type: boolean
        default: false
      gitref:
        description: "The git ref to check out from the specified repository."
        required: true
      changelog-entry:
        description: "Documentation for the changelog entry"
        required: true
      version-bump-type:
        description: "Type of version bump:minor|patch"
        required: false
        type: choice
        options:
          - minor
          - patch
        default: minor

concurrency:
  group: publish-airbyte-java-cdk
  cancel-in-progress: false

env:
  # Use the provided GITREF or default to the branch triggering the workflow.
  REPO: ${{ github.event.inputs.repo }}
  GITREF: ${{ github.event.inputs.gitref || github.ref }}
  DRY_RUN: "${{ github.event.inputs.dry-run == null && 'true' || github.event.inputs.dry-run }}"
  CHANGELOG_ENTRY: "${{ github.event.inputs.changelog-entry == null && 'tesT1' || github.event.inputs.changelog-entry }}"
  VERSION_BUMP_TYPE: "${{ github.event.inputs.version-bump-type == null && 'minor' || github.event.inputs.version-bump-type }}"

jobs:
  get_ci_runner:
    runs-on: ubuntu-latest
    name: Get CI runner
    steps:
      - name: Checkout Airbyte
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GH_PAT_APPROVINGTON_OCTAVIA }}
          fetch-depth: 1
      - name: Get CI runner
        id: get_ci_runner
        uses: ./.github/actions/airbyte-ci-requirements
        with:
          runner_type: "format"
          runner_size: "large"
          airbyte_ci_command: "cdk"
          github_token: ${{ secrets.GH_PAT_APPROVINGTON_OCTAVIA }}
          sentry_dsn: ${{ secrets.SENTRY_AIRBYTE_CI_DSN }}
    outputs:
      runner_name: ${{ steps.get_ci_runner.outputs.runner_name }}
  publish-java-cdk:
    name: "Run airbyte-ci cdk bump-version"
    needs: get_ci_runner
    runs-on: ${{ needs.get_ci_runner.outputs.runner_name }}
    steps:
      - name: Checkout Airbyte
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
          # Important that this is set so that CI checks are triggered again
          # Without this we would be forever waiting on required checks to pass
          token: ${{ secrets.GH_PAT_APPROVINGTON_OCTAVIA }}

      - name: Run airbyte-ci format fix all
        uses: ./.github/actions/run-dagger-pipeline
        continue-on-error: true
        with:
          context: "manual"
          dagger_cloud_token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
          docker_hub_password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          docker_hub_username: ${{ secrets.DOCKER_HUB_USERNAME }}
          gcs_credentials: ${{ secrets.METADATA_SERVICE_PROD_GCS_CREDENTIALS }}
          sentry_dsn: ${{ secrets.SENTRY_AIRBYTE_CI_DSN }}
          github_token: ${{ secrets.GH_PAT_MAINTENANCE_OCTAVIA }}
          tailscale_auth_key: ${{ secrets.TAILSCALE_AUTH_KEY }}
          subcommand: 'cdk bump-version $VERSION_BUMP_TYPE "$CHANGELOG_ENTRY"'
      - name: Bail out form here
        run: echo "VERSION_BUMP_TYPE=$VERSION_BUMP_TYPE, CHANGELOG_ENTRY=$CHANGELOG_ENTRY" && exit 1

      # This is helpful in the case that we change a previously committed generated file to be ignored by git.
      - name: Remove any files that have been gitignored
        run: git ls-files -i -c --exclude-from=.gitignore | xargs -r git rm --cached

      - name: Commit Java CDK Version Bump
        uses: stefanzweifel/git-auto-commit-action@v5
        # Don't commit if we're on master
        if: github.ref != 'refs/heads/master'
        with:
          commit_message: "Bumping java CDK version"
          commit_user_name: Octavia Squidington III
          commit_user_email: octavia-squidington-iii@users.noreply.github.com
